#Generated Form Function
function GenerateForm {
########################################################################
# Code Generated By: SAPIEN Technologies PrimalForms (Community Edition) v1.0.10.0
# Generated On: 05.10.2020 17:48
# Generated By: Luis Lüscher
########################################################################

#region Import the Assemblies
[reflection.assembly]::loadwithpartialname("System.Drawing") | Out-Null
[reflection.assembly]::loadwithpartialname("System.Windows.Forms") | Out-Null
#endregion

#region Generated Form Objects
$form1 = New-Object System.Windows.Forms.Form
$label2 = New-Object System.Windows.Forms.Label
$btn_cnl = New-Object System.Windows.Forms.Button
$comboBox1 = New-Object System.Windows.Forms.ComboBox
$textBox1 = New-Object System.Windows.Forms.TextBox
$label1 = New-Object System.Windows.Forms.Label
$btn_create = New-Object System.Windows.Forms.Button
$ch_acc = New-Object System.Windows.Forms.CheckBox
$ch_never = New-Object System.Windows.Forms.CheckBox
$ch_cantchange = New-Object System.Windows.Forms.CheckBox
$cb_chgpasswd = New-Object System.Windows.Forms.CheckBox
$txt_passconf = New-Object System.Windows.Forms.TextBox
$txt_pass = New-Object System.Windows.Forms.TextBox
$label_passwd = New-Object System.Windows.Forms.Label
$label_pass = New-Object System.Windows.Forms.Label
$txt_login = New-Object System.Windows.Forms.TextBox
$label_login = New-Object System.Windows.Forms.Label
$txt_last = New-Object System.Windows.Forms.TextBox
$label_last = New-Object System.Windows.Forms.Label
$label_first = New-Object System.Windows.Forms.Label
$txt_first = New-Object System.Windows.Forms.TextBox
$label_main = New-Object System.Windows.Forms.Label
$InitialFormWindowState = New-Object System.Windows.Forms.FormWindowState
#endregion Generated Form Objects

#Start Write-log function
    $path = "C:\Users\Administrator\Documents\scripts\ad_manager\Log"
    $date = get-date -Format "yyyy-MM-dd"
    $file = ("Log_" + $date + ".log")
    $logfile = $path + "\" + $file

    function Write-Log([string]$logtext, [int]$level = 0) {
        $logdate = get-date -Format "yyyy-MM-dd HH:mm:ss"
        if ($level -eq 0) {
            $logtext = "[INFO] " + $logtext
            $text = "[" + $logdate + "] - " + $logtext
        }
        $text >> $logfile
    }
    Write-Log "Starting add_user.ps1"

#Get AD Users
#$ous = Get-ADOrganizationalUnit -Filter * -Properties Name | Format-Table Name
$ous = Get-ADOrganizationalUnit -Filter 'Name -like "*"' -Properties Name

Foreach ($ou in $ous)
{
$comboBox1.Items.Add($ou);
}
Write-Log "Get AD OUs"

#----------------------------------------------
#Generated Event Script Blocks
#----------------------------------------------
#Provide Custom Code for events specified in PrimalForms.
$handler_textBox2_TextChanged= 
{
#TODO: Place custom script here

}

$handler_label3_Click= 
{
#TODO: Place custom script here

}

$handler_button2_Click= 
{
#TODO: Place custom script here
#CANCEL Button
.\delete_user.ps1

}

$handler_button1_Click= 
{
#TODO: Place custom script here
#Create User Button
Write-Log "Startet the sequence"
    #Setzen der $groupname Variable durch den Input aus txt Box.
    
    $global:firstname = $txt_first.text
    $global:lastname = $txt_last.text
    $global:loginname = $txt_login.text
    $global:password1 = $txt_pass.text
    $global:password2 = $txt_passconf.text
    $global:tel = $textbox1.text
    $global:ou = $comboBox1.SelectedItem

    #Vollständigkeit der Daten überprüfen
    if ($global:password1 -ne $global:password2){
    [System.Windows.Forms.MessageBox]::Show("Password doesn't match" , "ERROR")
    Write-Log "Password doesn't match ERROR"
    }
    elseif ($global:loginname -eq ''){
    [System.Windows.Forms.MessageBox]::Show("Please Type in Login name" , "ERROR")
    Write-Log "Please Type in Login name ERROR"
    }
    elseif ($global:firstname -eq ''){
    [System.Windows.Forms.MessageBox]::Show("Please Type in Firstname" , "ERROR")
    Write-Log "Please Type in Firstname ERROR"
    }
    elseif ($global:lastname -eq ''){
    [System.Windows.Forms.MessageBox]::Show("Please Type in lastname" , "ERROR")
    Write-Log "Please Type in lastname ERROR"
    }
    elseif ($global:password1 -eq ''){
    [System.Windows.Forms.MessageBox]::Show("Please Type in Password" , "ERROR")
    Write-Log "Please Type in Password1 ERROR"
    }
    elseif ($global:password2 -eq ''){
    [System.Windows.Forms.MessageBox]::Show("Please Type in Password" , "ERROR")
    Write-Log "Please Type in Password2 ERROR"
    }
    elseif ($global:tel -eq ''){
    [System.Windows.Forms.MessageBox]::Show("Please Type in Phone Number" , "ERROR")
    Write-Log "Please Type in Phone Numbe ERROR"
    }
    elseif ($global:ou -eq ''){
    [System.Windows.Forms.MessageBox]::Show("Please Select OU" , "ERROR")
    Write-Log "Please Select OU ERROR"
    }
    elseif ($cb_chgpasswd.Checked -and $ch_cantchange.Checked){
    [System.Windows.Forms.MessageBox]::Show("You can't Choose Change Password and no Password change" , "ERROR")
    Write-Log "You can't Choose Change Password and no Password change"
    }
    elseif ($cb_chgpasswd.Checked -and $ch_never.Checked){
    [System.Windows.Forms.MessageBox]::Show("You can't Choose Change Password and Password never expires" , "ERROR")
    Write-Log "You can't Choose Change Password and Password never expires"
    }
    else 
    {
        $secureString = ConvertTo-SecureString $global:password2 -AsPlainText -Force

        $name = $global:firstname + " " + $global:lastname

        $givenname = $global:firstname

        $surname = $global:lastname

        $SamAccountName = $global:loginname

        $UserPrincipalName = "$global:loginname@base.dom"

        $orgu = $global:ou

        $mobilephone = $global:tel
        
        if ($cb_chgpasswd.Checked)
        {
        
 

        New-ADUser -Name $name -GivenName $givenname -Surname $surname -SamAccountName $SamAccountName -UserPrincipalName $UserPrincipalName -AccountPassword $secureString -Enabled $true -Path $orgu -ChangePasswordAtLogon $true 
        
        Set-ADUser -Identity $SamAccountName -OfficePhone $mobilephone

        $form1.close()

        }
        elseif ($ch_cantchange.Checked)
        {

        New-ADUser -Name $name -GivenName $givenname -Surname $surname -SamAccountName $SamAccountName -UserPrincipalName $UserPrincipalName -AccountPassword $secureString -Enabled $true -Path $orgu -CannotChangePassword $true

        Set-ADUser -Identity $SamAccountName -OfficePhone $mobilephone

        $form1.close()

        }
        elseif ($ch_never.Checked)
        {
 
        New-ADUser -Name $name -GivenName $givenname -Surname $surname -SamAccountName $SamAccountName -UserPrincipalName $UserPrincipalName -AccountPassword $secureString -Enabled $true -Path $orgu -PasswordNeverExpires $true

        Set-ADUser -Identity $SamAccountName -OfficePhone $mobilephone

        $form1.close()

        }
        elseif ($ch_acc.Checked)
        {

        New-ADUser -Name $name -GivenName $givenname -Surname $surname -SamAccountName $SamAccountName -UserPrincipalName $UserPrincipalName -AccountPassword $secureString -Enabled $true -Path $orgu -Enabled $false

        Set-ADUser -Identity $SamAccountName -OfficePhone $mobilephone

        $form1.close()

        }
        else
        {

        New-ADUser -Name $name -GivenName $givenname -Surname $surname -SamAccountName $SamAccountName -UserPrincipalName $UserPrincipalName -AccountPassword $secureString -Enabled $true -Path $orgu

 

        Set-ADUser -Identity $SamAccountName -OfficePhone $mobilephone

        $form1.close()

        }

        Write-Log "Created user"
        [System.Windows.Forms.MessageBox]::Show("User created" , "SUCCESS")

}
}

$handler_label6_Click= 
{
#TODO: Place custom script here

}

$handler_textBox3_TextChanged= 
{
#TODO: Place custom script here

}

$handler_label4_Click= 
{
#TODO: Place custom script here

}

$handler_textBox1_TextChanged= 
{
#TODO: Place custom script here

}

$handler_label2_Click= 
{
#TODO: Place custom script here

}

$handler_label1_Click= 
{
#TODO: Place custom script here

}

$OnLoadForm_StateCorrection=
{#Correct the initial state of the form to prevent the .Net maximized form issue
	$form1.WindowState = $InitialFormWindowState
}

#----------------------------------------------
#region Generated Form Code
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 292
$System_Drawing_Size.Width = 532
$form1.ClientSize = $System_Drawing_Size
$form1.DataBindings.DefaultDataSourceUpdateMode = 0
$form1.Name = "form1"
$form1.Text = "Create new User for base.dom"

$label2.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 62
$System_Drawing_Point.Y = 232
$label2.Location = $System_Drawing_Point
$label2.Name = "label2"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 21
$System_Drawing_Size.Width = 70
$label2.Size = $System_Drawing_Size
$label2.TabIndex = 20
$label2.Text = "OU:"
$label2.add_Click($handler_label2_Click)

$form1.Controls.Add($label2)


$btn_cnl.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 364
$System_Drawing_Point.Y = 257
$btn_cnl.Location = $System_Drawing_Point
$btn_cnl.Name = "btn_cnl"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 75
$btn_cnl.Size = $System_Drawing_Size
$btn_cnl.TabIndex = 19
$btn_cnl.Text = "Delete User"
$btn_cnl.UseVisualStyleBackColor = $True
$btn_cnl.add_Click($handler_button2_Click)

$form1.Controls.Add($btn_cnl)

$comboBox1.DataBindings.DefaultDataSourceUpdateMode = 0
$comboBox1.FormattingEnabled = $True
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 149
$System_Drawing_Point.Y = 229
$comboBox1.Location = $System_Drawing_Point
$comboBox1.Name = "comboBox1"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 21
$System_Drawing_Size.Width = 200
$comboBox1.Size = $System_Drawing_Size
$comboBox1.TabIndex = 18

$form1.Controls.Add($comboBox1)

$textBox1.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 149
$System_Drawing_Point.Y = 202
$textBox1.Location = $System_Drawing_Point
$textBox1.Name = "textBox1"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 20
$System_Drawing_Size.Width = 100
$textBox1.Size = $System_Drawing_Size
$textBox1.TabIndex = 17

$form1.Controls.Add($textBox1)

$label1.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 62
$System_Drawing_Point.Y = 205
$label1.Location = $System_Drawing_Point
$label1.Name = "label1"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 70
$label1.Size = $System_Drawing_Size
$label1.TabIndex = 16
$label1.Text = "Tel.:"

$form1.Controls.Add($label1)


$btn_create.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 439
$System_Drawing_Point.Y = 257
$btn_create.Location = $System_Drawing_Point
$btn_create.Name = "btn_create"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 81
$btn_create.Size = $System_Drawing_Size
$btn_create.TabIndex = 15
$btn_create.Text = "Create User"
$btn_create.UseVisualStyleBackColor = $True
$btn_create.add_Click($handler_button1_Click)

$form1.Controls.Add($btn_create)


$ch_acc.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 286
$System_Drawing_Point.Y = 149
$ch_acc.Location = $System_Drawing_Point
$ch_acc.Name = "ch_acc"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 24
$System_Drawing_Size.Width = 205
$ch_acc.Size = $System_Drawing_Size
$ch_acc.TabIndex = 14
$ch_acc.Text = "Account is disabled"
$ch_acc.UseVisualStyleBackColor = $True

$form1.Controls.Add($ch_acc)


$ch_never.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 286
$System_Drawing_Point.Y = 122
$ch_never.Location = $System_Drawing_Point
$ch_never.Name = "ch_never"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 24
$System_Drawing_Size.Width = 205
$ch_never.Size = $System_Drawing_Size
$ch_never.TabIndex = 13
$ch_never.Text = "Password never expires"
$ch_never.UseVisualStyleBackColor = $True

$form1.Controls.Add($ch_never)


$ch_cantchange.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 286
$System_Drawing_Point.Y = 96
$ch_cantchange.Location = $System_Drawing_Point
$ch_cantchange.Name = "ch_cantchange"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 24
$System_Drawing_Size.Width = 205
$ch_cantchange.Size = $System_Drawing_Size
$ch_cantchange.TabIndex = 12
$ch_cantchange.Text = "User cannot change password"
$ch_cantchange.UseVisualStyleBackColor = $True

$form1.Controls.Add($ch_cantchange)


$cb_chgpasswd.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 286
$System_Drawing_Point.Y = 70
$cb_chgpasswd.Location = $System_Drawing_Point
$cb_chgpasswd.Name = "cb_chgpasswd"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 24
$System_Drawing_Size.Width = 205
$cb_chgpasswd.Size = $System_Drawing_Size
$cb_chgpasswd.TabIndex = 11
$cb_chgpasswd.Text = "User must change password"
$cb_chgpasswd.UseVisualStyleBackColor = $True

$form1.Controls.Add($cb_chgpasswd)

$txt_passconf.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 149
$System_Drawing_Point.Y = 177
$txt_passconf.Location = $System_Drawing_Point
$txt_passconf.Name = "txt_passconf"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 20
$System_Drawing_Size.Width = 100
$txt_passconf.Size = $System_Drawing_Size
$txt_passconf.TabIndex = 10

$form1.Controls.Add($txt_passconf)

$txt_pass.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 149
$System_Drawing_Point.Y = 151
$txt_pass.Location = $System_Drawing_Point
$txt_pass.Name = "txt_pass"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 20
$System_Drawing_Size.Width = 100
$txt_pass.Size = $System_Drawing_Size
$txt_pass.TabIndex = 9

$form1.Controls.Add($txt_pass)

$label_passwd.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 62
$System_Drawing_Point.Y = 180
$label_passwd.Location = $System_Drawing_Point
$label_passwd.Name = "label_passwd"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 100
$label_passwd.Size = $System_Drawing_Size
$label_passwd.TabIndex = 8
$label_passwd.Text = "Password:"
$label_passwd.add_Click($handler_label6_Click)

$form1.Controls.Add($label_passwd)

$label_pass.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 62
$System_Drawing_Point.Y = 154
$label_pass.Location = $System_Drawing_Point
$label_pass.Name = "label_pass"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 100
$label_pass.Size = $System_Drawing_Size
$label_pass.TabIndex = 7
$label_pass.Text = "Password:"

$form1.Controls.Add($label_pass)

$txt_login.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 149
$System_Drawing_Point.Y = 124
$txt_login.Location = $System_Drawing_Point
$txt_login.Name = "txt_login"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 20
$System_Drawing_Size.Width = 100
$txt_login.Size = $System_Drawing_Size
$txt_login.TabIndex = 6
$txt_login.add_TextChanged($handler_textBox3_TextChanged)

$form1.Controls.Add($txt_login)

$label_login.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 62
$System_Drawing_Point.Y = 127
$label_login.Location = $System_Drawing_Point
$label_login.Name = "label_login"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 100
$label_login.Size = $System_Drawing_Size
$label_login.TabIndex = 5
$label_login.Text = "Login Name:"
$label_login.add_Click($handler_label4_Click)

$form1.Controls.Add($label_login)

$txt_last.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 149
$System_Drawing_Point.Y = 98
$txt_last.Location = $System_Drawing_Point
$txt_last.Name = "txt_last"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 20
$System_Drawing_Size.Width = 100
$txt_last.Size = $System_Drawing_Size
$txt_last.TabIndex = 4
$txt_last.add_TextChanged($handler_textBox2_TextChanged)

$form1.Controls.Add($txt_last)

$label_last.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 62
$System_Drawing_Point.Y = 101
$label_last.Location = $System_Drawing_Point
$label_last.Name = "label_last"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 70
$label_last.Size = $System_Drawing_Size
$label_last.TabIndex = 3
$label_last.Text = "Last Name:"
$label_last.add_Click($handler_label3_Click)

$form1.Controls.Add($label_last)

$label_first.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 62
$System_Drawing_Point.Y = 75
$label_first.Location = $System_Drawing_Point
$label_first.Name = "label_first"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 17
$System_Drawing_Size.Width = 70
$label_first.Size = $System_Drawing_Size
$label_first.TabIndex = 2
$label_first.Text = "First Name:"
$label_first.add_Click($handler_label2_Click)

$form1.Controls.Add($label_first)

$txt_first.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 149
$System_Drawing_Point.Y = 72
$txt_first.Location = $System_Drawing_Point
$txt_first.Name = "txt_first"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 20
$System_Drawing_Size.Width = 100
$txt_first.Size = $System_Drawing_Size
$txt_first.TabIndex = 1
$txt_first.add_TextChanged($handler_textBox1_TextChanged)

$form1.Controls.Add($txt_first)

$label_main.DataBindings.DefaultDataSourceUpdateMode = 0
$label_main.Font = New-Object System.Drawing.Font("Microsoft Sans Serif",18,0,3,1)

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 158
$System_Drawing_Point.Y = 9
$label_main.Location = $System_Drawing_Point
$label_main.Name = "label_main"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 39
$System_Drawing_Size.Width = 216
$label_main.Size = $System_Drawing_Size
$label_main.TabIndex = 0
$label_main.Text = "Create User"
$label_main.TextAlign = 2
$label_main.add_Click($handler_label1_Click)

$form1.Controls.Add($label_main)

#endregion Generated Form Code

#Save the initial state of the form
$InitialFormWindowState = $form1.WindowState
#Init the OnLoad event to correct the initial state of the form
$form1.add_Load($OnLoadForm_StateCorrection)
#Show the Form
$form1.ShowDialog()| Out-Null

} #End Function

#Call the Function
GenerateForm
